version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: desafio_postgres
    environment:
      POSTGRES_DB: desafio_db
      POSTGRES_USER: Nakaya
      POSTGRES_PASSWORD: Nakaya123
    ports:
      - "8000:8000"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 